export const ALL_PERMISSIONS = {
    RESTAURANTS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/restaurants', module: "RESTAURANTS" },
        CREATE: { method: "POST", apiPath: '/api/v1/restaurants', module: "RESTAURANTS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/restaurants', module: "RESTAURANTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/restaurants/{id}', module: "RESTAURANTS" },
    },
    CLIENTS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/clients', module: "CLIENTS" },
        CREATE: { method: "POST", apiPath: '/api/v1/clients', module: "CLIENTS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/clients', module: "CLIENTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/clients/{id}', module: "CLIENTS" },
    },
    USERS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/users', module: "USERS" },
        CREATE: { method: "POST", apiPath: '/api/v1/users', module: "USERS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/users', module: "USERS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/users/{id}', module: "USERS" },
    },
    ROLES: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/roles', module: "ROLES" },
        CREATE: { method: "POST", apiPath: '/api/v1/roles', module: "ROLES" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/roles', module: "ROLES" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/roles/{id}', module: "ROLES" },
    },
    PERMISSIONS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/permissions', module: "PERMISSIONS" },
        CREATE: { method: "POST", apiPath: '/api/v1/permissions', module: "PERMISSIONS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/permissions', module: "PERMISSIONS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/permissions/{id}', module: "PERMISSIONS" },
    },
    DININGTABLES: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/dining-tables', module: "DININGTABLES" },
        CREATE: { method: "POST", apiPath: '/api/v1/dining-tables', module: "DININGTABLES" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/dining-tables', module: "DININGTABLES" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/dining-tables/{id}', module: "DININGTABLES" },
    },
    SUPPLIERS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/suppliers', module: "SUPPLIERS" },
        CREATE: { method: "POST", apiPath: '/api/v1/suppliers', module: "SUPPLIERS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/suppliers', module: "SUPPLIERS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/suppliers/{id}', module: "SUPPLIERS" },
    },
    ORDERS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/orders', module: "ORDERS" },
        CREATE: { method: "POST", apiPath: '/api/v1/orders', module: "ORDERS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/orders', module: "ORDERS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/orders/{id}', module: "ORDERS" },
    },
    PRODUCTS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/products', module: "PRODUCTS" },
        CREATE: { method: "POST", apiPath: '/api/v1/products', module: "PRODUCTS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/products', module: "PRODUCTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/products/{id}', module: "PRODUCTS" },
    },
    INGREDIENTS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/ingredients', module: "INGREDIENTS" },
        CREATE: { method: "POST", apiPath: '/api/v1/ingredients', module: "INGREDIENTS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/ingredients', module: "INGREDIENTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/ingredients/{id}', module: "INGREDIENTS" },
    },
    INVOICES: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/invoices', module: "INVOICES" },
        CREATE: { method: "POST", apiPath: '/api/v1/invoices', module: "INVOICES" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/invoices', module: "INVOICES" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/invoices/{id}', module: "INVOICES" },
    },
    RECEIPTS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/receipts', module: "RECEIPTS" },
        CREATE: { method: "POST", apiPath: '/api/v1/receipts', module: "RECEIPTS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/receipts', module: "RECEIPTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/receipts/{id}', module: "RECEIPTS" },
    },
    REVIEWS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/reviews', module: "REVIEWS" },
        CREATE: { method: "POST", apiPath: '/api/v1/reviews', module: "REVIEWS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/reviews', module: "REVIEWS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/reviews/{id}', module: "REVIEWS" },
    },
    SHIFTS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/shifts', module: "SHIFTS" },
        CREATE: { method: "POST", apiPath: '/api/v1/shifts', module: "SHIFTS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/shifts', module: "SHIFTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/shifts/{id}', module: "SHIFTS" },
    },
    FEEDBACKS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/feedbacks', module: "FEEDBACKS" },
        CREATE: { method: "POST", apiPath: '/api/v1/feedbacks', module: "FEEDBACKS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/feedbacks', module: "FEEDBACKS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/feedbacks/{id}', module: "FEEDBACKS" },
    },
}

export const ALL_MODULES = {
    USERS: 'USERS',
    FILES: 'FILES',
    ROLES: 'ROLES',
    SHIFTS: 'SHIFTS',
    ORDERS: 'ORDERS',
    CLIENTS: 'CLIENTS',
    REVIEWS: 'REVIEWS',
    INVOICES: 'INVOICES',
    RECEIPTS: 'RECEIPTS',
    PRODUCTS: 'PRODUCTS',
    SUPPLIERS: 'SUPPLIERS',
    FEEDBACKS: 'FEEDBACKS',
    RESTAURANTS: 'RESTAURANTS',
    PERMISSIONS: 'PERMISSIONS',
    INGREDIENTS: 'INGREDIENTS',
    DININGTABLES: 'DININGTABLES',
}
